# baseURL = "https://Jiri-Kremser.github.io"
# languageCode = "en-us"
# title = "Jirka Kremser"
# theme = "m10c"
# paginate = 5

# [params]
#   author = "Jirka Kremser"
#   description = "Full-stack software engineer working at Red Hat and open source enthusiast."

# [[params.social]]
#   name = "github"
#   url = "https://github.com/Jiri-Kremser"

# [[params.social]]
#   name = "twitter"
#   url = "https://twitter.com/JirkaKremser"

# [[params.social]]
#   name = "linkedin"
#   url = "https://www.linkedin.com/in/jirik/"

# [[params.social]]
#   name = "message-square"
#   url = "mailto:jkremser@redhat.com"

# [[params.social]]
#   name = "code"
#   url = "https://stackoverflow.com/users/1594980/jiri-kremser"

# # [[params.social]]
# #   name = "phone"
# #   url = "sdfsf"

baseURL = "https://jkremser.github.io"
languageCode = "en-us"
title = "Jirka Kremser"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Jirka Kremser"
    description = "Full-stack software engineer working at Red Hat and open source enthusiast."
    githubUsername = "Jiri-Kremser"
    accent = "#1a574a"
    showBorder = true
    backgroundColor = "#dfe2e5"
    profilePic = "avatar.png"
    # should match the name on Google Fonts!
    # font = "Raleway"
    font = "Montserrat"
    # font = "Archivo"
    # font = "Karla"
    # font = "Rubik"
    # font = "Source Sans"
    # font = "Cardo"
    # font = "Work Sans"
    # font = "Arvo"
    # font = "Lato"
    # font = "Ubuntu"
    # font = "Oxygen"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/presentation/"
    name = "Presentations"
    weight = 4



# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/



[[menu.icon]]
    url = "https://github.com/Jiri-Kremser/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/JirkaKremser/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/jirik/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://stackoverflow.com/users/1594980/jiri-kremser"
    name = "stack-overflow"
    weight = 4

[[menu.icon]]
    url = "mailto:jkremser@redhat.com"
    name = "envelope-o"
    weight = 5
